version: '3.9'

services:
  # Rest API
  ecommerce-api:
    image: ecommerce-api
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - ecommerce-db-sql
    environment:
      NODE_ENV: production
      DATABASE_URL: 
    ports:
      - 3000:3000

  # MySQL Database
  ecommerce-db-sql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: 
      MYSQL_ROOT_PASSWORD: 
    volumes:
      - ecommerce-data:/var/lib/mysql

volumes:
  ecommerce-data:
