version: '3.4'

services:
  ecommerce-api:
    image: ecommerce-api
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
